---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zrc.
--- DateTime: 2023/7/19 21:17
---
--- 比骄傲线程标识与锁中的标识是否一致
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0